[project]
name = "Textclassifier"
version = "0.0.1"
authors = [
  { name="Malte Autrata", email="malte.autrata@smail.th-koeln.de" },
]
description = "A package for all classifier models."
readme = "README.md"
requires-python = ">=3.10"